### ISSUE TITLE
Maximizing window on secondary monitor jumps to main monitor and messes up tiling there.

### ISSUE THREAD

**Issue by StFS** [faho/kwin-tiling#32]
Just some comments about my experience with multimonitor setup.

I have a huge (32" - 2560x1440) main screen and a very small secondary screen (19" - 1280x1024).

Tiling is only active on my main screen and not on the secondary screen. This is actually fine by me but I'm guessing some people would like to have tiling on both screens. I would like to have a config option that would enable me to choose which monitor tiling is active on and which not. I would even prefer to be able to choose which virtual desktop tiling is enabled on so that I can have one virtual desktop with "normal" floating windows and the rest using tiling (and even some virtual desktops where one monitor is floating but the other one tiling etc.).

The main problem that I'm experiencing though is when I have a window on my secondary monitor and I try to maximize it, it jumps over to the main screen and gets maximized there. Furthermore it messes up the whole tiling of the main monitor.

**Comment by faho** [comment]
I'm guessing this is fixed in a88c2ffc5da394ac0fb0e18fa72ff65bc3139bf1.

**Comment by piotr-dobrogost** [comment]
I'm observing window jumping to another screen when being maximized.
Could we have this bug reopened and could somebody please confirm that issue with maximization is still present?
Wondering if https://github.com/kwin-scripts/kwin-tiling/issues/130 could help here anyhow?
